config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show, :index]
  resources :passengers, only: [:index]
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight", inverse_of: :from_airport
  has_many :arriving_flights, foreign_key: :to_airport_id, class_name: "Flight", inverse_of: :to_airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_and_belongs_to_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", inverse_of: :departing_flights
  belongs_to :to_airport, class_name: "Airport", inverse_of: :arriving_flights
  has_many :bookings

  scope :departing_dates, -> {
    find_by_sql("SELECT DISTINCT(strftime('%d/%m/%Y', departing_time)) as departing_date FROM \"flights\"")
  }

  def travel_time
    elapsed = arriving_time - departing_time
    ActiveSupport::Duration.build(elapsed)
  end

  # @param utc_offset [Integer]
  # @return [Time]
  def departing_time_local(utc_offset = from_airport.timezone)
    departing_time.localtime(utc_offset * 3600)
  end

  # @param utc_offset [Integer]
  # @return [Time]
  def arriving_time_local(utc_offset = to_airport.timezone)
    arriving_time.localtime(utc_offset * 3600)
  end

  # @return [String]
  def departing_date_formatted
    departing_time.strftime("%d/%m/%Y")
  end

  def to_s
    dt = "[#{departing_time_local.strftime("%H:%M") }]"
    at = "[#{arriving_time_local.strftime("%H:%M") }]"
    "#{from_airport.code} #{dt} --{ #{travel_time.parts[:hours]} h }--> #{to_airport.code} #{at}"
  end
end

app/models/params_search.rb
class ParamsSearch < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"

  # @return [String]
  def departing_date_formatted
    return nil if departing_date.nil?
    departing_date.strftime("%d/%m/%Y")
  end

  def flights
    Flight.where(
      "from_airport_id = ? AND to_airport_id = ? AND capacity >= ? AND strftime('%d/%m/%Y', departing_time) = ?",
      from_airport_id,
      to_airport_id,
      passengers,
      departing_date_formatted
    )
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_and_belongs_to_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    redirect_to root_path unless params.key?(:params_search)

    permitted = params.require(:params_search).permit(:flights, :passengers)
    @flight = Flight.find(permitted[:flights].to_i)
    @booking = Booking.new
    permitted[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    redirect_to new_booking_path unless params.key?(:booking)

    permitted = params.require(:booking).permit(:flight_id, :passengers_attributes => {})
    @booking = Booking.new(flight_id: permitted[:flight_id].to_i)
    permitted[:passengers_attributes].each do |i, pa|
      founded = Passenger.find_by(email: pa[:email])
      if founded.nil?
        @booking.passengers.build(pa)
      else
        @booking.passengers << founded
      end
    end
    @booking.save
    redirect_to booking_path(@booking)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all.order(:created_at).reverse_order
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = nil
    if !params.key?(:commit)
      @search_params = ParamsSearch.new
    else
      @search_params = ParamsSearch.new(search_params)
      @flights = @search_params.flights
    end
  end

  def search_params
    permitted = params.permit(:from_airport, :to_airport, :passengers, :departing_date)
    {
      :from_airport_id => permitted[:from_airport],
      :to_airport_id => permitted[:to_airport],
      :passengers => permitted[:passengers],
      :departing_date => permitted[:departing_date]
    }
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def index
    @passengers = Passenger.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container bg-light shadow-sm rounded py-2">
  <h3 align="center">Bookings</h3>
  <ul class="list-group">
    <% @bookings.each do |b| %>
      <a class="list-group-item list-group-item-action" href="<%= booking_path(b) %>">
        <span>Booking code: <%= b.id %></span>
      </a>
    <% end %>
  </ul>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <div class="container bg-light shadow-sm rounded py-2 mt-2">
    <h3 align="center">Booking</h3>
    <div class="container border border-secondary py-2">
      <h5>Flight</h5>
      <span>
      <i>Aircraft capacity: </i> <%= @flight.capacity %>
    </span><br>
      <span>
      <i>Code: </i> <%= @flight.id %>
    </span>
    </div>
    <div class="container border border-secondary py-2">
      <h5>Airport</h5>
      <span>
      <i>From:</i> <%= @flight.from_airport.name %>
        [<strong><%= @flight.from_airport.code %></strong>]
    </span><br>
      <span>
      <i>To:</i> <%= @flight.to_airport.name %>
        [<strong><%= @flight.to_airport.code %></strong>]
    </span>
    </div>
    <div class="container border border-secondary py-2">
      <h5>Dates</h5>
      <span><i>Departing:</i> <%= @flight.departing_time_local %></span><br>
      <span><i>Arriving:</i> <%= @flight.arriving_time_local %></span><br>
      <span><i>Fly time:</i> <%= @flight.travel_time.parts[:hours] %> hours</span><br>
      <small><span> * Dates showed by airports local time</span></small>
    </div>

    <div class="container border border-secondary py-2">
      <h5>Passengers</h5>

      <%= f.hidden_field :flight_id, value: @flight.id %>
      <%= f.simple_fields_for :passengers do |pf| %>
        <div class="container d-flex justify-content-start gap-3">
          <%= pf.input :name, required: true, label: false do %>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  Name
                </div>
              </div>
              <%= pf.input_field :name, class: "form-control" %>
            </div>
          <% end %>
          <%= pf.input :email, required: true, label: false do %>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  E-mail
                </div>
              </div>
              <%= pf.input_field :email, class: "form-control" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= f.submit value: "Booking", class: "btn btn-primary my-2" %>
  </div>
<% end %>

app/views/bookings/show.html.erb
<div class="container bg-light shadow-sm rounded py-2 mt-2">
  <h3 align="center">Booking №<%= @booking.id %></h3>
  <div class="container border border-secondary py-2">
    <h5>Flight</h5>
    <span>
      <i>Aircraft capacity: </i> <%= @booking.flight.capacity %>
    </span><br>
    <span>
      <i>Code: </i> <%= @booking.flight.id %>
    </span>
  </div>
  <div class="container border border-secondary py-2">
    <h5>Airport</h5>
    <span>
      <i>From:</i> <%= @booking.flight.from_airport.name %>
      [<strong><%= @booking.flight.from_airport.code %></strong>]
    </span><br>
    <span>
      <i>To:</i> <%= @booking.flight.to_airport.name %>
      [<strong><%= @booking.flight.to_airport.code %></strong>]
    </span>
  </div>
  <div class="container border border-secondary py-2">
    <h5>Dates</h5>
    <span><i>Departing:</i> <%= @booking.flight.departing_time_local %></span><br>
    <span><i>Arriving:</i> <%= @booking.flight.arriving_time_local %></span><br>
    <span><i>Fly time:</i> <%= @booking.flight.travel_time.parts[:hours] %> hours</span><br>
    <small><span> * Dates showed by airports local time</span></small>
  </div>
  <div class="container border border-secondary py-2">
    <h5>Passengers</h5>
    <ul class="list-group">
      <% @booking.passengers.each do |p| %>
        <li class="list-group-item d-flex justify-content-around">
          <span><%= p.name %></span>
          <span><%= p.email %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/flights/index.html.erb
<div class="container bg-light shadow-sm rounded py-2">
  <h3 align="center">Flight Search</h3>
  <%= simple_form_for @search_params, url: root_path, method: "get" do |f| %>
    <div class="container py-1">
      <span>
        From:
        <%= select_tag "from_airport",
                       options_from_collection_for_select(Airport.all, :id, :name,
                                                          selected: @search_params.from_airport_id) %>
      </span>
      <span>
        To:
        <%= select_tag "to_airport",
                       options_from_collection_for_select(Airport.all, :id, :name,
                                                          selected: @search_params.to_airport_id) %>
      </span>
    </div>
    <div class="container py-1">
      <span>Date:</span>
      <%= select_tag "departing_date",
                     options_from_collection_for_select(Flight.departing_dates, :departing_date, :departing_date,
                                                        selected: @search_params.departing_date_formatted) %>
    </div>
    <div class="container py-1">
      <span>Passengers:</span>
      <%= select_tag "passengers", options_for_select([1, 2, 3, 4], @search_params.passengers) %>
    </div>
    <div class="container py-1 mt-1">
      <%= f.submit value: "Search", class: "btn btn-outline-primary" %>
    </div>
  <% end %>
</div>



<% unless @flights.nil? %>
  <div class="container bg-light shadow-sm rounded py-2 mt-3">
    <h3 align="center">Founded</h3>
    <% if @flights.count.zero? %>
      <div class="alert alert-dark">
        No results
      </div>
    <% else %>
      <%= simple_form_for @search_params, url: new_booking_path, method: "get" do |f| %>
        <ul class="list-group rounded">
          <%= f.collection_radio_buttons :flights, @search_params.flights, :id, :to_s do |b| %>
            <li class="list-group-item">
              <%= b.label(:"data-value" => b.value) { b.radio_button(class: "mx-2") + b.text } %>
            </li>
          <% end %>
          <%= f.input :passengers, as: :hidden %>
          <div class="container mx-0 px-0 mt-3">
            <%= f.submit value: "Booking on this date", class: "btn btn-outline-primary" %>
          </div>

        </ul>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm mb-3">
  <div class="container-fluid">
    <%= link_to 'Flight Booking', root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Flights', flights_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Last Bookings', bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Passengers', passengers_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% flash.each do |type, msg| %>
  <% type = type == 'alert' ? 'warning' : 'success' %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/passengers/index.html.erb
<div class="container bg-light shadow-sm rounded py-2">
  <h3 align="center">Passengers</h3>
  <ul class="list-group">
    <% @passengers.each do |p| %>
      <li class="list-group-item d-flex justify-content-around">
        <span><%= p.name %></span>
        <span><%= p.email %></span>
      </li>
    <% end %>
  </ul>
</div>